# Generated by Django 3.1.1 on 2021-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('isCurrentUser', models.BooleanField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('wasprocessed', models.BooleanField()),
                ('userid', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WordsGuessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordid', models.IntegerField(default=0)),
                ('letter', models.CharField(max_length=1)),
                ('guessed', models.BooleanField()),
            ],
        ),
    ]
